[project]
name = "maple-font"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "foundrytools-cli>=1.1.22",
    "glyphslib>=6.10.1",
]
